### ISSUE TITLE
Typo execut

### ISSUE THREAD

**Issue by spalen0** [Schlagonia/tokenized-strategy-periphery-ape#6]
HealtCheck contract has function [`_executHealthCheck()`](https://github.com/Schlagonia/tokenized-strategy-periphery/blob/168c8a6b887396378f8e14a6fec64ab0e80fcaef/contracts/HealthCheck/HealthCheck.sol#L80).

In the title description, it is referenced as [`_executeHealthCheck()`](https://github.com/Schlagonia/tokenized-strategy-periphery/blob/168c8a6b887396378f8e14a6fec64ab0e80fcaef/contracts/HealthCheck/HealthCheck.sol#L18).

Old Vaults use `execute`: https://github.com/yearn/yearn-vaults/blob/97ca1b2e4fcf20f4be0ff456dabd020bfeb6697b/contracts/CommonHealthCheck.sol#L116

**Comment by Schlagonia** [comment]
fixed on new repo https://github.com/Schlagonia/tokenized-strategy-periphery/pulls
